sudo: required
os:
  - linux

services:
  - docker

language: node_js
node_js:
  - "8"
  - "10"

before_install:
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - sudo apt-get update && sudo apt-get install google-cloud-sdk google-cloud-sdk-datastore-emulator
  - docker pull google/cloud-sdk:latest
  - printenv
  - 'if [ "${TRAVIS_NODE_VERSION}" = "8" ]; then
        npm install -g greenkeeper-lockfile@1;
    fi'

before_script:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "8" ]; then
        greenkeeper-lockfile-update;
    fi'

after_script:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "8" ]; then
        greenkeeper-lockfile-upload;
    fi'
